export const GET_DETAILS_START = 'GET_DETAILS_START';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAILED = 'GET_DETAILS_FAILED';

export const GET_EPISODES_START = 'GET_EPISODES_START';
export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_FAILED = 'GET_EPISODES_FAILED';
